name: Check
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python installation
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Create venv
        run: python -m venv venv

      - name: Activate venv
        run: source venv/bin/activate

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: python -m unittest discover tests
    