name: Check
on:
  push:
    branches: [ 'main', 'feature/**']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python installation
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Create venv
        run: python -m venv venv

      - name: Activate venv
        run: source venv/bin/activate

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: python -m unittest discover tests
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKERHUB_REPO }}